BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DOCKERFILES="${BASEDIR}/Dockerfiles"
DOCKERFILES_ADMIN="${DOCKERFILES}/admin"
DOCKERFILES_ALLINONE="${DOCKERFILES}/allinone"
DOCKERFILES_PRESENTATION="${DOCKERFILES}/presentation"
DOCKERFILES_WORKER="${DOCKERFILES}/worker"
