version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    target-branch: 19.x # set to oldest supported major versions
    groups:
      all:
        patterns: [ "*" ]
    labels:
      - kind/dependency
