# Copyright 2016 The WWU eLectures Team All rights reserved.
#
# Licensed under the Educational Community License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/ECL-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

volumes:
  db: {}
  opensearch: {}
  data: {}

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: opencast
      POSTGRES_USER: opencast
      POSTGRES_PASSWORD: opencast
    volumes:
      - db:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:1
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: -Xms128m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: true
      DISABLE_SECURITY_PLUGIN: true
    volumes:
      - opensearch:/usr/share/opensearch/data

  opencast:
    image: quay.io/opencast/allinone:13.1
    environment:
      ORG_OPENCASTPROJECT_SERVER_URL: http://localhost:8080
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: http://localhost:8080/static
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: admin
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: opencast
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: opencast_system_account
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: CHANGE_ME
      ORG_OPENCASTPROJECT_DB_VENDOR: PostgreSQL
      ORG_OPENCASTPROJECT_DB_JDBC_URL: jdbc:postgresql://postgresql/opencast
      ORG_OPENCASTPROJECT_DB_JDBC_USER: opencast
      ORG_OPENCASTPROJECT_DB_JDBC_PASS: opencast
      ELASTICSEARCH_SERVER_HOST: opensearch
    ports:
      - "8080:8080"
    volumes:
      - data:/data
