name: Update Container Images

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDX_OUTPUT: --push
      DOCKER_BUILDX_PLATFORM: linux/amd64,linux/arm64

    strategy:
      fail-fast: false
      matrix:
        include:
          # dev
          - { day_of_week: '*', branch: '21.x', push_major: 'true' }
          - { day_of_week: '*', branch: '20.x' }
          - { day_of_week: '*', branch: '19.x' }
          - { day_of_week: '*', branch: '18.x' }

          # stable
          - { day_of_week: '0', branch: '20.2', push_major: 'true', additional_tags: 'latest' }
          - { day_of_week: '1', branch: '20.1' }
          - { day_of_week: '2', branch: '20.0' }

          # legacy
          - { day_of_week: '3', branch: '19.7', push_major: 'true' }
          - { day_of_week: '4', branch: '19.6' }
          - { day_of_week: '5', branch: '19.5' }
          - { day_of_week: '6', branch: '18.8', push_major: 'true' }

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ matrix.branch }}

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
        with:
          platforms: ${{ env.DOCKER_BUILDX_PLATFORM }}

      - name: set up OCI registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: build and push container images
        run: |
          if [ "${{ matrix.day_of_week }}" != "*" ]; then
            if [ "${{ matrix.day_of_week }}" != $(date "+%w") ]; then
              echo "Not scheduled for today; done"
              exit
            fi
          fi

          IMAGE_TAGS="$(cat VERSION)"
          if [ "${{ matrix.push_major }}" = 'true' ]; then
            IMAGE_TAGS="${IMAGE_TAGS} $(cat VERSION_MAJOR)"
          fi
          if [ -n "${{ matrix.additional_tags }}" ]; then
            IMAGE_TAGS="${IMAGE_TAGS} ${{ matrix.additional_tags }}"
          fi

          BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ")

          # retry once
          for i in $(seq 1 2); do
            make \
              BUILD_DATE="${BUILD_DATE}" \
              IMAGE_TAGS="${IMAGE_TAGS}" \
              DOCKER_BUILDX_PLATFORM="${DOCKER_BUILDX_PLATFORM}" \
              DOCKER_BUILDX_OUTPUT="${DOCKER_BUILDX_OUTPUT}" \
              build \
            && break
          done
